server:
  port: 8088

spring:
  application:
    name: chinsmall-gateway

  ## nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    ## 网关
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            #          如果带了参数url，且参数值是baidu
            - Query=url, baidu
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            #          如果带了参数url，且参数值是qq
            - Query=url, qq


        #           商品服务路由
        - id: product_route
          uri: lb://chinsmall-product
          predicates:
            - Path=/api/product/**
          filters:
            #            /api/product/category/list/tree -> /product/category/list/tree
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        #         renren-fast后台
        - id: admin_route
          uri: lb://renren-fast:8080
          predicates:
          #            前端请求以api开头
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}